#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-thrift
Version  : 0.9.3
Release  : 3
URL      : https://repo1.maven.org/maven2/org/apache/thrift/libthrift/0.9.3/libthrift-0.9.3.jar
Source0  : https://repo1.maven.org/maven2/org/apache/thrift/libthrift/0.9.3/libthrift-0.9.3.jar
Source1  : https://repo.maven.apache.org/maven2/org/apache/thrift/libfb303/0.9.0/libfb303-0.9.0.jar
Source2  : https://repo.maven.apache.org/maven2/org/apache/thrift/libfb303/0.9.0/libfb303-0.9.0.pom
Source3  : https://repo.maven.apache.org/maven2/org/apache/thrift/libfb303/0.9.3/libfb303-0.9.3.jar
Source4  : https://repo.maven.apache.org/maven2/org/apache/thrift/libfb303/0.9.3/libfb303-0.9.3.pom
Source5  : https://repo1.maven.org/maven2/org/apache/thrift/libthrift/0.9.0/libthrift-0.9.0.jar
Source6  : https://repo1.maven.org/maven2/org/apache/thrift/libthrift/0.9.0/libthrift-0.9.0.pom
Source7  : https://repo1.maven.org/maven2/org/apache/thrift/libthrift/0.9.1/libthrift-0.9.1.pom
Source8  : https://repo1.maven.org/maven2/org/apache/thrift/libthrift/0.9.2/libthrift-0.9.2.jar
Source9  : https://repo1.maven.org/maven2/org/apache/thrift/libthrift/0.9.2/libthrift-0.9.2.pom
Source10  : https://repo1.maven.org/maven2/org/apache/thrift/libthrift/0.9.3/libthrift-0.9.3.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-thrift-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-thrift package.
Group: Data

%description data
data components for the mvn-thrift package.


%prep
%setup -q -n META-INF

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/thrift/libthrift/0.9.3
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/apache/thrift/libthrift/0.9.3/libthrift-0.9.3.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/thrift/libfb303/0.9.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/apache/thrift/libfb303/0.9.0/libfb303-0.9.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/thrift/libfb303/0.9.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/apache/thrift/libfb303/0.9.0/libfb303-0.9.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/thrift/libfb303/0.9.3
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/apache/thrift/libfb303/0.9.3/libfb303-0.9.3.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/thrift/libfb303/0.9.3
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/apache/thrift/libfb303/0.9.3/libfb303-0.9.3.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/thrift/libthrift/0.9.0
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/apache/thrift/libthrift/0.9.0/libthrift-0.9.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/thrift/libthrift/0.9.0
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/apache/thrift/libthrift/0.9.0/libthrift-0.9.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/thrift/libthrift/0.9.1
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/apache/thrift/libthrift/0.9.1/libthrift-0.9.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/thrift/libthrift/0.9.2
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/org/apache/thrift/libthrift/0.9.2/libthrift-0.9.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/thrift/libthrift/0.9.2
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/org/apache/thrift/libthrift/0.9.2/libthrift-0.9.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/thrift/libthrift/0.9.3
cp %{SOURCE10} %{buildroot}/usr/share/java/.m2/repository/org/apache/thrift/libthrift/0.9.3/libthrift-0.9.3.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/apache/thrift/libfb303/0.9.0/libfb303-0.9.0.jar
/usr/share/java/.m2/repository/org/apache/thrift/libfb303/0.9.0/libfb303-0.9.0.pom
/usr/share/java/.m2/repository/org/apache/thrift/libfb303/0.9.3/libfb303-0.9.3.jar
/usr/share/java/.m2/repository/org/apache/thrift/libfb303/0.9.3/libfb303-0.9.3.pom
/usr/share/java/.m2/repository/org/apache/thrift/libthrift/0.9.0/libthrift-0.9.0.jar
/usr/share/java/.m2/repository/org/apache/thrift/libthrift/0.9.0/libthrift-0.9.0.pom
/usr/share/java/.m2/repository/org/apache/thrift/libthrift/0.9.1/libthrift-0.9.1.pom
/usr/share/java/.m2/repository/org/apache/thrift/libthrift/0.9.2/libthrift-0.9.2.jar
/usr/share/java/.m2/repository/org/apache/thrift/libthrift/0.9.2/libthrift-0.9.2.pom
/usr/share/java/.m2/repository/org/apache/thrift/libthrift/0.9.3/libthrift-0.9.3.jar
/usr/share/java/.m2/repository/org/apache/thrift/libthrift/0.9.3/libthrift-0.9.3.pom
